theme: jekyll-theme-minimal
title: Yuki Arase
description: Associate professor, Osaka University </br> arase[at]ist.osaka-u.ac.jp 
show_downloads: false
google_analytics: UA-209098895-1
logo: /assets/img/yuki_arase_2020.jpg